server:
  port: 8081
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    #    database-platform: mysql
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/order?serverTimezone=UTC&characterEncoding=UTF-8
      username: order-svc
      password: order-pass
  flyway:
    user: order-svc
    password: order-pass
    schemas: order
    url: jdbc:mysql://localhost:3307/order?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true
    # mail
  mail:
    host: smtp.gamil.com
    port: 587
    username: test@gmail.com
    password: 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  config: classpath:logback-local.xml

# aws sqs
cloud:
  aws:
    access-key: AKIAZ43H435T2BDT5FQL
    secret-key: 9LQ4xT3RSJ1bkRtmn8zN2yimosuyT/cGlAFd5Wxn

# coolsms
example.sms:
  apikey: NCSFE93O6OB7YOZZ
  apisecret: 1YNIWXTTDUWBXL98M6CSQH85LGGICZ2J
  phone: '01011112222'


